config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "movies#index"
  get "/movies/new", to: "movies#new"

  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    post 'bookmarks', to: 'bookmarks#create'
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie_id, presence: true, uniqueness: { scope: :list_id, message: "Movie and List pair must be unique"}
  validates :list_id, presence: true

  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true

  has_many :bookmarks
  has_many :lists, through: :bookmarks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list_id = params[:list_id]

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def index
    @lists = List.all
  end

  def create
    @list = List.new(list_params)
    puts @list.photo
    puts "what I print out is above"
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    puts @list
    puts "what I print out is above"
    @movies = @list.movies
    puts @movies
    puts "what I print out is above"
    @bookmark = Bookmark.new
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_path, notice: "List was successfully destroyed." }
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to :root do%>
    <i class="fa-solid fa-video"></i>
  <% end %>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "My lists", lists_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New list", new_list_path, class:"nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "layouts/navbar" %>

      <div class="content">
        <%= yield %>
      </div>

      <footer class="footer">
      <div class="text-center p-4">
    © 2025 Copyright:
    <a class="text-reset fw-bold" href="#">Amy's work.com</a>
      </div>
    </footer>
    </div>
  </body>
</html>

app/views/lists/_card.html.erb
<div class="col-md-4 col-sm-6 mb-3">
  <div class="card" style="width: 100%;">
  <%= cl_image_tag list.photo.key.to_s, class: "card-img-top" %>
  <div class="card-body">
    <%= link_to list.name, list_path(list), class: "card-title" %>
  </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="background">
  <p class="title">Lists</p>
  <%= image_tag "banner.jpeg", height: 400, style: "width: 100%" %>
</div>
<div class="container">
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4 col-sm-6 mb-3 card-position">
        <%= link_to list_path(list), class: "card list-background", style: "width: 100%;" do %>
          <p class="list-title"><%= list.name %></p>
          <%= cl_image_tag list.photo.key.to_s, class: "card-img-top" %>
        <% end %>
        <!-- 刪除按鈕 -->
        <%= link_to list_path(list), data: { turbo_confirm: "Are you sure?", turbo_method: "delete" }, style: "position: absolute; top: 10px; right: 30px; z-index: 20; color: white; font-size: 25px" do %>
            <i class="fa-solid fa-circle-xmark"></i>
          <% end %>
          <!-- 刪除按鈕 -->
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container" style="padding-top: 40px">
  <%= simple_form_for @list, method: :post do |f| %>
    <div class="form-inputs">
      <%= f.input :name, label: "What's the name of the list?"%>
      <%= f.input :photo, as: :file%>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
      <%= link_to 'Go to Home', root_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="single-container">
  <div>
    <h1>Movies in List: <%=@list.name%></h1>
  </div>
  <div class="row">
    <% @movies.each do |movie| %>
      <%= render 'movies/card', movie: movie %>
    <% end %>
  </div>

  <div>
    <h1>Let's add more movies into this list!</h1>
  </div>

  <div>
    <%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-inputs">
    <%= f.association :movie, label: "What's the movie you want to pick?"%>
  </div>
  <div class="form-inputs">
    <%= f.input :comment, as: :text, label: "Leave your comment"%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Go to Home', root_path, class: 'btn btn-secondary' %>
  </div>
  <% end %>
  </div>
</div>

app/views/movies/_card.html.erb
<div class="col-md-4 col-sm-6 mb-3">
  <div class="card" style="width: 100%;">
  <%= image_tag movie.poster_url, class: "card-img-top" %>
  <div class="card-body">
    <h5 class="card-title"><%= movie.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= movie.overview %></h6>
  </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="background">
  <p class="title">Movies</p>
  <%= image_tag "theater.jpg", height: 400, style: "width: 100%" %>
</div>
<div class="container">
  <%= link_to movies_new_path, class: "btn btn-primary add-movie-btn" do %>
    Add my own movie
  <% end %>

  <div class="row">
    <% @movies.each do |movie| %>
      <%= render "card", movie: movie%>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="container" style="padding-top: 40px">
<%= simple_form_for @movie, url: :root, method: :post do |f| %>
  <div class="form-inputs">
    <%= f.input :title, label: "What's the title of the movie?"%>
    <%= f.input :overview, as: :text, label: "What's the overview of this movie?"%>
    <%= f.input :poster_url, label: "Please paste the url of the poster for this movie."%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Go to Home', root_path, class: 'btn btn-secondary' %>
  </div>
<% end %>
</div>